FROM ruby:2.7.2

ENV INSTALL_PATH /opt/app

RUN mkdir -p $INSTALL_PATH

ENV INSTALL_PATH /opt/app

RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY / .

RUN gem install rails bundler

RUN bundle install

CMD bundle exec unicorn -c config/unicorn.rb
