default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: walrus

development:
  <<: *default
  adapter: async

test:
  <<: *default
  adapter: test

production:
  <<: *default
