{
  "ruby.rubocop.executePath": "/usr/local/bin/rubocop",
  "ruby.rubocop.configFilePath": "./.rubocop.yml",
  "ruby.rubocop.onSave": true,
  "editor.tabSize": 1,
  "[ruby]": {
      "editor.tabSize": 1
  },
  "[javascript]": {
      "editor.tabSize": 1
  },
  "[json]": {
      "editor.tabSize": 1
  },
  "editor.insertSpaces": true,
  "files.trimTrailingWhitespace": true,
  "vetur.format.styleInitialIndent": true,
  "vetur.format.scriptInitialIndent": true,
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
      "javascript",
      "javascriptreact",
      {
          "language": "vue",
          "autoFix": true
      }
  ],
  "prettier.disableLanguages": [],
  "editor.formatOnSave": true,
  "prettier.eslintIntegration": true,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatterOptions": {
      "js-beautify-html": {},
      "prettyhtml": {
          "printWidth": 80,
          "singleQuote": false
      }
  },
  "stylusSupremacy.insertColons": false,
  "stylusSupremacy.insertLeadingZeroBeforeFraction": false,
  "stylusSupremacy.insertSemicolons": false,
  "stylusSupremacy.insertBraces": false,
  "workbench.editor.enablePreviewFromQuickOpen": false,
  "workbench.editor.enablePreview": false
}
