name: CI

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Permissions
        run: |
          sudo mkdir -p /tmp/cache
          sudo chown -R $(whoami) /tmp/cache
          sudo chmod 777 log
          sudo chmod 777 tmp
          sudo chmod 777 db

      - name: Build the stack
        run: docker-compose build

      - name: Prepare stuff
        run: docker-compose run walrus rake db:create db:migrate

      - name: Coverage
        run: docker-compose run -e COVERAGE=true walrus rspec
