name: CI

on: [pull_request]

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Permissions
        run: sudo chown -R $(whoami):$(whoami) /opt/app

      - name: Build the stack
        run: docker-compose build

      - name: Prepare stuff
        run: |
          docker-compose run walrus rake db:create RAILS_ENV=test
          docker-compose run walrus rake db:schema:load RAILS_ENV=test

      - name: Rubocop Default
        run: docker-compose run walrus rubocop --regenerate-todo --parallel

      - name: Rails Best Practices PR Rubies Only
        run: docker-compose run walrus rails_best_practices --format html --only

      - name: Coverage PR Specs Only
        run: docker-compose run -e COVERAGE=true walrus rspec

      - name: RSpec All
        run: docker-compose run walrus rspec
